//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineExpotronica2019.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cineEntities : DbContext
    {
        public cineEntities()
            : base("name=cineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<funcion> funcion { get; set; }
        public virtual DbSet<pelicula> pelicula { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    
        public virtual int compraBoletos(string idFuncion)
        {
            var idFuncionParameter = idFuncion != null ?
                new ObjectParameter("idFuncion", idFuncion) :
                new ObjectParameter("idFuncion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("compraBoletos", idFuncionParameter);
        }
    }
}
